Import('env', 'raft_o')

PhonyTargets(env, gtest_svn = 'svn checkout http://googletest.googlecode.com/svn/trunk/ gtest')

env.StaticObject("gtest-all.o",
        "#gtest/src/gtest-all.cc",
        CPPPATH = [ "#gtest", "#gtest/include" ],
        CPPFLAGS = [ "-g", "-DDEBUG" ],
        CXXFLAGS = "-std=c++0x")

env.Program("test", 
        source = (["test_runner.cpp", "node_tests.cpp", "log_tests.cpp", "tcp_server_tests.cpp", "gtest-all.o"] + raft_o), 
        LIBS = ["pthread", "protobuf", "boost_system"],
        LIBPATH = ["#build/raft"],
        CPPPATH = ["#gtest/include", "#src", "#build/raft"])

env.Program("tcp_server", 
        source = (["tcp_server.cpp"] + raft_o), 
        LIBS = ["pthread", "protobuf", "boost_system"],
        LIBPATH = ["#build/raft"],
        CPPPATH = ["#gtest/include", "#src", "#build/raft"])

env.Program("tcp_client", 
        source = (["tcp_client.cpp"] + raft_o), 
        LIBS = ["pthread", "protobuf", "boost_system"],
        LIBPATH = ["#build/raft"],
        CPPPATH = ["#gtest/include", "#src", "#build/raft"])
