Import('env')

raft_o = env.StaticObject(
        ["node.cpp", "log.cpp"],
        CPPPATH = [],
        CPPFLAGS = [ "-g", "-DDEBUG" ],
        CXXFLAGS = "-std=c++11")

env.StaticLibrary("raft",
        source = raft_o,
        CPPPATH = [],
        CPPFLAGS = [ "-g", "-DDEBUG" ],
        CXXFLAGS = "-std=c++11")

