Import('env')

env.StaticObject("raft.o",
                 "#src/node.cpp",
                 CPPPATH = [],
                 CPPFLAGS = [ "-g", "-DDEBUG" ],
                 CXXFLAGS = "-std=c++11")

env.StaticLibrary("raft", 
        source = "raft.o", 
        CPPPATH = [],
        CPPFLAGS = [ "-g", "-DDEBUG" ],
        CXXFLAGS = "-std=c++11")

